server:
  host: "0.0.0.0"
  port: 50051
  worker_threads: 4    # gRPC 业务线程数

ai_brain:
  vla_model_path: "../models/dummy_vla.onnx"
  intra_op_threads: 2  # 视觉大模型推理需要的 CPU 线程数
  use_gpu: true        # 明确开启 GPU 加速

robot:
  camera_topic: "/camera/image_raw"
  cmd_topic: "/cmd_vel"